const jadwalsholat = require("./lib/jadwalsholat");
const {
    version: version,
    author: author
} = require("./package.json"), 
binary = require("./lib/binary"),
iplookup = require("./lib/tools/iplook"),
artinama = require("./lib/search/artinama"), 
stress = require("./lib/stress"), 
cuaca = require("./lib/cuaca"), 
youtube = require("./lib/downloader/youtube"), 
fakeua = require("./lib/tools/fakeua"), 
tiktok2 = require("./lib/downloader/tiktok2"), 
tiktok = require("./lib/downloader/tiktok"), 
igstalk = require("./lib/igstalk"), 
carigrup = require("./lib/grupwa"), 
happymod = require("./lib/happymod"), 
kusonime = require("./lib/kusonime"), 
emojimix = require("./lib/tools/emojimix"), 
translate = require("./lib/translate"), 
rangkum = require("./lib/rangkum"), 
film = require("./lib/film"), 
wallpapercave = require("./lib/wallpapercave"), 
family100 = require("./lib/game/family100"), 
soundcloud = require("./lib/downloader/soundcloud"), 
whois = require("./lib/tools/whois"), 
getHeaders = require("./lib/tools/headers"), 
shortlink = require("./lib/tools/shortlink"), 
uploadFile = require("./lib/tools/uploadFile"), 
uploadFile2 = require("./lib/tools/uploadFile2"), 
minifyjs = require("./lib/tools/minifyjs"), 
siapakahaku = require("./lib/game/siapakahaku"), 
EncryptHTML = require("./lib/tools/enc-html"), 
isporn = require("./lib/tools/is-porn"), 
persamaankata = require("./lib/persamaankata"), 
singkatankata = require("./lib/singkatankata"), 
quran = require("./lib/religion/alquran"), 
instagram = require("./lib/downloader/instagram"), 
freefireid = require("./lib/freefireid"), 
wall_alphacoders = require("./lib/wall.alphacoders.js"), 
quotesanime = require("./lib/random/quotesanime"), 
mediafire = require("./lib/downloader/mediafire"), 
ttstalk = require("./lib/ttstalk"), 
urlexpand = require("./lib/urlexpand"),
gempa = require("./lib/infogempa"), 
pindl = require("./lib/downloader/pindl"), 
pin = require("./lib/pinsrch"), 
soundcloud2 = require("./lib/soundcloudsearch"), 
textpro = require("./lib/tools/textpro"), 
sfile = require("./lib/sfile"), 
chordlagu = require("./lib/chordlagu"), 
subfinder = require("./lib/tools/subfinder"), 
tiklydown = require("./lib/downloader/tiklydown"),
playstore = require("./lib/playstore"),
corona = require("./lib/covid"),
cerpen = require("./lib/cerpen"),
ssweb = require("./lib/tools/ssweb"),
lirik = require("./lib/lyrics"),
kisahnabi = require("./lib/religion/kisahnabi"),
{ jadwaltv } = require("./lib/jadwaltv"),
listsurah = require("./lib/religion/listsurah"),
sholat = require("./lib/religion/jadwalsholat"),
{ tebakgambar } = require("./lib/game/tebakgambar");

module.exports = {
    version: version,
    author: author,
    info: {
        gempa: gempa
    },
    encrypt: {
        binary: binary
    },
    stress: stress,
    downloader: {
        yt: youtube,
        tiktok: tiktok,
        tiktok2: tiktok2,
        soundcloud: soundcloud,
        instagram: instagram,
        mediafire: mediafire,
        pindl: pindl,
        tiklydown: tiklydown
    },
    search: {
        jadwaltv: jadwaltv,
        listsurah: listsurah,
        playstore: playstore,
        corona: corona,
        cerpen: cerpen,
        kisahnabi: kisahnabi,
        happymod: happymod,
        carigrup: carigrup,
        sholat: sholat,
        kusonime: kusonime,
        iplookup: iplookup,
        cuaca: cuaca,
        lirik: lirik,
        artinama: artinama,
        igstalk: igstalk,
        cuaca: cuaca,
        film: film,
        wallpapercave: wallpapercave,
        singkatankata: singkatankata,
        persamaankata: persamaankata,
        quran: quran,
        freefireid: freefireid,
        wall_alphacoders: wall_alphacoders,
        ttstalk: ttstalk,
        pin: pin,
        soundcloud: soundcloud2,
        sfile: sfile,
        chordlagu: chordlagu
    },
    random: {
        fakeua: fakeua,
        quotesanime: quotesanime
    },
    other: {
        emojimix: emojimix,
        translate: translate,
        rangkum: rangkum
    },
    tools: {
        ssweb: ssweb,
        whois: whois,
        getHeaders: getHeaders,
        shortlink: shortlink,
        uploadFile: uploadFile,
        uploadFile2: uploadFile2,
        minifyjs: minifyjs,
        EncryptHTML: EncryptHTML,
        expandurl: urlexpand,
        isporn: isporn,
        textpro: textpro,
        subfinder: subfinder
    },
    game: {
        tebakgmbr: tebakgambar,
        family100: family100,
        siapakahaku: siapakahaku
    }
};